# Generated by Django 4.2.1 on 2023-05-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_description',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Status description'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Tracking number'),
        ),
    ]
