# Generated by Django 4.2.1 on 2023-05-11 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_add_order_status_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='client',
        ),
    ]
